modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/bedrock-miner/issues"

[[mods]]
modId="bedrockminer"
version="2.2.1"
displayName="Bedrock Miner"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/BedrockMiner.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bedrock-miner"
itemIcon="minecraft:bedrock"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''Adds tools to harvest bedrock and craft things like blocks, items and armor out of it!'''

[[dependencies.bedrockminer]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bedrockminer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.3)"
    ordering="NONE"
    side="BOTH"
