modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/bedrock-miner/issues"

[[mods]]
modId="bedrockminer"
version="2.0.0-pre1"
displayName="Bedrock Miner"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/BedrockMiner.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bedrock-miner"
itemIcon="minecraft:bedrock"
logoFile="logo.png"
#credits="Thanks for this "
authors="XxRexRaptorxX (RexRaptor)"
description='''
This small mod adds a new stable tool set to the game, the pickaxe and the breaker machine allows you to mine bedrock. With this new resource can you craft a few new items and blocks :D
'''

[[dependencies.bedrockminer]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bedrockminer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
